/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DiscussRouteImport } from './routes/discuss'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemsSlugRouteImport } from './routes/problems.$slug'
import { Route as ContestsIdRouteImport } from './routes/contests.$id'

const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussRoute = DiscussRouteImport.update({
  id: '/discuss',
  path: '/discuss',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsSlugRoute = ProblemsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProblemsRoute,
} as any)
const ContestsIdRoute = ContestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contests': typeof ContestsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/discuss': typeof DiscussRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRoute
  '/contests/$id': typeof ContestsIdRoute
  '/problems/$slug': typeof ProblemsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contests': typeof ContestsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/discuss': typeof DiscussRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRoute
  '/contests/$id': typeof ContestsIdRoute
  '/problems/$slug': typeof ProblemsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contests': typeof ContestsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/discuss': typeof DiscussRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRoute
  '/contests/$id': typeof ContestsIdRoute
  '/problems/$slug': typeof ProblemsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contests'
    | '/dashboard'
    | '/discuss'
    | '/leaderboard'
    | '/login'
    | '/problems'
    | '/profile'
    | '/register'
    | '/settings'
    | '/submissions'
    | '/contests/$id'
    | '/problems/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contests'
    | '/dashboard'
    | '/discuss'
    | '/leaderboard'
    | '/login'
    | '/problems'
    | '/profile'
    | '/register'
    | '/settings'
    | '/submissions'
    | '/contests/$id'
    | '/problems/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contests'
    | '/dashboard'
    | '/discuss'
    | '/leaderboard'
    | '/login'
    | '/problems'
    | '/profile'
    | '/register'
    | '/settings'
    | '/submissions'
    | '/contests/$id'
    | '/problems/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContestsRoute: typeof ContestsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DiscussRoute: typeof DiscussRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProblemsRoute: typeof ProblemsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SubmissionsRoute: typeof SubmissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discuss': {
      id: '/discuss'
      path: '/discuss'
      fullPath: '/discuss'
      preLoaderRoute: typeof DiscussRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$slug': {
      id: '/problems/$slug'
      path: '/$slug'
      fullPath: '/problems/$slug'
      preLoaderRoute: typeof ProblemsSlugRouteImport
      parentRoute: typeof ProblemsRoute
    }
    '/contests/$id': {
      id: '/contests/$id'
      path: '/$id'
      fullPath: '/contests/$id'
      preLoaderRoute: typeof ContestsIdRouteImport
      parentRoute: typeof ContestsRoute
    }
  }
}

interface ContestsRouteChildren {
  ContestsIdRoute: typeof ContestsIdRoute
}

const ContestsRouteChildren: ContestsRouteChildren = {
  ContestsIdRoute: ContestsIdRoute,
}

const ContestsRouteWithChildren = ContestsRoute._addFileChildren(
  ContestsRouteChildren,
)

interface ProblemsRouteChildren {
  ProblemsSlugRoute: typeof ProblemsSlugRoute
}

const ProblemsRouteChildren: ProblemsRouteChildren = {
  ProblemsSlugRoute: ProblemsSlugRoute,
}

const ProblemsRouteWithChildren = ProblemsRoute._addFileChildren(
  ProblemsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContestsRoute: ContestsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DiscussRoute: DiscussRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProblemsRoute: ProblemsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SubmissionsRoute: SubmissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
